### ISSUE TITLE
target multiple architectures

### ISSUE THREAD

**Issue by travi** [semantic-release/docker-gitbox#4]
Our maintainers are all now using M1 macbooks and have found that this image currently does not work with ARM architectures. We could republish supporting multiple architectures by following a guide similar to [this one](https://dev.to/tidalmigrations/multi-cpu-architecture-container-images-how-to-build-and-push-them-on-docker-hub-or-any-other-registry-2981). 

I tried doing so and ended up publishing https://hub.docker.com/r/travi/docker-gitbox (after resolving an issue through https://github.com/semantic-release/docker-gitbox/pull/3) with the intent of re-publishing again under the semantic-release org, but it still fails. It does overcome the architecture limitation, but results in a different error that does not happen when running on x86. So, probably still related to architecture somehow, but unsure why so far. 

the new error is as follows:
```
/etc/init.d/fcgiwrap start
[FAIL] Starting FastCGI wrapper: fcgiwrap failed!
```

my docker knowledge is super rusty but i didnt find additional information about the error in logs from the container or other details to point to a good next step.

**Comment by travi** [comment]
this problem is preventing integration tests from running in https://github.com/semantic-release/semantic-release. 

there is a lot of outdated stuff in this image that could be updated, but keep in mind that unblocking https://github.com/semantic-release/semantic-release/issues/2478 could be handled to switching to a different image, so it would be best to keep changes in this image to a minimum to prove that fixing this path is viable before spending time/effort on updating the image for other reasons.

**Comment by travi** [comment]
@jsoref since it looks like you've been using this image, have you possibly already solved this issue? if not would you be interested in investigating?

**Comment by jsoref** [comment]
I don't think I was using it directly. You're right that I have an M1 and have actually done porting work for a handful of projects that didn't have proper cross abi things. (Fwiw, GitHub's roadmap currently shows that M1s will be arriving.)

I do have a todo item for this repository, but it isn't that kind of build stuff. 

Personally, I tend to use `strace` to wrap things and then just read the logs.

If you don't have any access to an m1, I might be able to allocate some time to look into this. But you should probably be able to reproduce it using Rancher and linux-aarch64 (or just an AWS cheap aarch64 spot instance or similar, I spun one of those up earlier this week).

**Comment by travi** [comment]
> Fwiw, GitHub's roadmap currently shows that M1s will be arriving.

i did see that, so linking here for reference: https://github.com/github/roadmap/issues/528. once those are available, i definitely plan to add them to our build matrix for each project

> If you don't have any access to an m1

my primary machine is an M1 at this point, which is a big part of why this is an issue for us, but i'm weak with debugging things like this at this point. spending all the time that i have available for project maintenance has been frustrating and has distracted from other needs of the projects. at this point, we're looking for help from the community to get us past this blocker.

however, please don't feel more obligated to contribute because i pinged you directly. just wanted to check in to see since you are/were using this image. no worries if you don't have the time for this one.
